version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://localhost:3000
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped
    networks:
      - talento-tech-network

  # Base de datos PostgreSQL (para futuras implementaciones)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: talento_tech
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - talento-tech-network

  # Redis para caché y sesiones (para futuras implementaciones)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - talento-tech-network

networks:
  talento-tech-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 